//Do not edit this file (unless you know what you are doing)

#ifndef SOLUTION_H
#define SOLUTION_H

#include"matrix.h"
#include"ode_solver.h"


class solution
{
	friend ostream &operator<<(ostream &, const solution &);
public:
	double A1, A2, A3, e_dot, T;
	double ro[1000];
	int pom1 = 0;
	int start;
	matrix x;
	matrix g;
	matrix H;
	matrix y;
	static int f_calls;
	static int g_calls;
	static int H_calls;
	static void clear_calls();
	solution(double = NAN);
	solution(const matrix &);
	solution(double *, int);
	void fit_fun(matrix = 0.0);
	void grad(matrix = 0.0);
	void hess(matrix = 0.0);
	double f(double A1,double A2, double A3, double e_dot,matrix x, double t, double y, double tcr,double* ro);
	double euler(double A1, double A2, double A3, double e_dot, matrix xmat,double x, double y, double x0, double y0, double h, double tcr,double Rocr, double* ro);
};

#endif